### ISSUE TITLE
[KDE/Wayland/fcitx5] Emoji in list are huge

### ISSUE THREAD

**Issue by Elteeb96** [GaZaTu/ibus-test#18]
When invoking the picker the emoji within the list are absolutely massive. I am running a triple monitor setup, could it perhaps be related to the pixel scaling in EmojiLabel.cpp? I would dig into it myself but I don't have the time atm.

Attached is an image of the issue (also wouldn't mind a dark mode :p)

![image](https://github.com/user-attachments/assets/6c9ec969-85a6-4685-8066-237246c5e68d)

**Comment by GaZaTu** [comment]
@Elteeb96 you're using the default emoji picker provided by fcitx5, you may need to disable it first.
![Screenshot_20240930_112643](https://github.com/user-attachments/assets/e8ad24bc-9bc8-471d-87da-d591488afee4)
